# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: callapp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='callapp.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rcallapp.proto\"\x1d\n\x0c\x43\x61llAppQuery\x12\r\n\x05query\x18\x01 \x01(\t\"#\n\x0f\x43\x61llAppResponse\x12\x10\n\x08response\x18\x01 \x01(\t2>\n\x07\x43\x61llApp\x12\x33\n\x0eGetCallAppData\x12\r.CallAppQuery\x1a\x10.CallAppResponse\"\x00\x62\x06proto3')
)




_CALLAPPQUERY = _descriptor.Descriptor(
  name='CallAppQuery',
  full_name='CallAppQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='CallAppQuery.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=46,
)


_CALLAPPRESPONSE = _descriptor.Descriptor(
  name='CallAppResponse',
  full_name='CallAppResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='CallAppResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['CallAppQuery'] = _CALLAPPQUERY
DESCRIPTOR.message_types_by_name['CallAppResponse'] = _CALLAPPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CallAppQuery = _reflection.GeneratedProtocolMessageType('CallAppQuery', (_message.Message,), dict(
  DESCRIPTOR = _CALLAPPQUERY,
  __module__ = 'callapp_pb2'
  # @@protoc_insertion_point(class_scope:CallAppQuery)
  ))
_sym_db.RegisterMessage(CallAppQuery)

CallAppResponse = _reflection.GeneratedProtocolMessageType('CallAppResponse', (_message.Message,), dict(
  DESCRIPTOR = _CALLAPPRESPONSE,
  __module__ = 'callapp_pb2'
  # @@protoc_insertion_point(class_scope:CallAppResponse)
  ))
_sym_db.RegisterMessage(CallAppResponse)



_CALLAPP = _descriptor.ServiceDescriptor(
  name='CallApp',
  full_name='CallApp',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=85,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCallAppData',
    full_name='CallApp.GetCallAppData',
    index=0,
    containing_service=None,
    input_type=_CALLAPPQUERY,
    output_type=_CALLAPPRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALLAPP)

DESCRIPTOR.services_by_name['CallApp'] = _CALLAPP

# @@protoc_insertion_point(module_scope)
